import type { Locale } from "./config";

const additions = {
  es: [
    { heading: "Project Clarity: datos del diagnóstico", body: "Project Clarity recoge las respuestas a seis preguntas sobre el tipo de proyecto, el bloqueo, los sistemas existentes, el resultado observable, las restricciones y el idioma. Para poder responder también solicita nombre y email; web y ubicación son opcionales. Turnstile y una referencia de idempotencia ayudan a limitar abuso y duplicados." },
    { heading: "Tránsito y almacenamiento", body: "Cloudflare valida y guarda temporalmente la solicitud en una cola acotada. Resend puede transportar una notificación al propietario. Los campos saneados y el informe validado se almacenan en un vault de leads separado, nunca en el vault personal del propietario." },
    { heading: "Inferencia local y revisión humana", body: "La primera lectura asistida por Gemma se ejecutará de forma asíncrona en el ordenador del propietario, no en el navegador del visitante. El modelo recibirá solo los campos saneados y conocimiento público aprobado. Ninguna decisión comercial ni email se envía de forma autónoma: Thomas revisa el informe y cualquier borrador antes de responder." },
    { heading: "Conservación y eliminación de Project Clarity", body: "La conservación operativa prevista es de 30 días desde la recepción. Los registros vencidos de la cola Cloudflare pueden purgarse mediante el worker privado; las notas locales vencidas pasan primero a una papelera recuperable y su eliminación definitiva requiere confirmación humana. Puedes solicitar una eliminación anticipada escribiendo a bonjour@thomas-nicoli.com." },
    { heading: "Chat inteligente y resúmenes por email", body: "Cloudflare guarda el mensaje y un contexto reciente acotado en una cola segura. Un modelo Gemma open source ejecutado localmente por Ollama en el ordenador de Thomas genera la respuesta; ningún proveedor de IA de pago recibe el contenido. Después de cada turno procesado, un resumen se envía automáticamente por Resend a Thomas. El chat no solicita el email del visitante y avisa de no compartir datos sensibles." },
    { heading: "Sesión y conservación del chat", body: "Turnstile abre una sesión anónima de dos horas, limitada a doce turnos. La dirección IP solo se usa en forma de hash para seguridad y límites de uso. Mensaje, respuesta, resumen y metadatos mínimos se conservan durante 30 días y pueden eliminarse antes solicitándolo a bonjour@thomas-nicoli.com." },
  ],
  en: [
    { heading: "Project Clarity diagnostic data", body: "Project Clarity collects answers to six questions about project type, the blockage, existing systems, the observable outcome, constraints and response language. It also requests a name and email so a reply is possible; website and location are optional. Turnstile and an idempotency reference help limit abuse and duplicates." },
    { heading: "Transit and storage", body: "Cloudflare validates and temporarily stores the request in a bounded queue. Resend may carry an owner notification. Sanitised fields and the validated report are stored in a separate lead vault, never in the owner's personal vault." },
    { heading: "Local inference and human review", body: "The Gemma-assisted first read will run asynchronously on the owner's computer, not in the visitor's browser. The model receives only sanitised fields and approved public knowledge. No commercial decision or email is sent autonomously: Thomas reviews the report and every draft before replying." },
    { heading: "Project Clarity retention and deletion", body: "The planned operational retention period is 30 days from receipt. Expired Cloudflare queue records can be purged through the private worker; expired local notes first move to recoverable trash and permanent deletion requires human confirmation. You can request earlier deletion at bonjour@thomas-nicoli.com." },
    { heading: "Intelligent chat and email summaries", body: "Cloudflare places the message and a bounded amount of recent context in a secure queue. An open-source Gemma model running locally through Ollama on Thomas's computer generates the reply; no paid AI provider receives the content. After every processed turn, an interaction summary is automatically emailed to Thomas through Resend. The chat does not request the visitor's email and warns against sharing sensitive data." },
    { heading: "Chat session and retention", body: "Turnstile opens an anonymous two-hour session limited to twelve turns. The IP address is used only as a hash for security and usage limits. The message, reply, summary and minimal metadata are retained for 30 days and can be deleted earlier on request to bonjour@thomas-nicoli.com." },
  ],
  fr: [
    { heading: "Données du diagnostic Project Clarity", body: "Project Clarity recueille les réponses à six questions sur le type de projet, le blocage, les systèmes existants, le résultat observable, les contraintes et la langue de réponse. Un nom et un email sont demandés pour pouvoir répondre ; le site et la localisation restent optionnels. Turnstile et une référence d'idempotence limitent les abus et doublons." },
    { heading: "Transit et stockage", body: "Cloudflare valide et stocke temporairement la demande dans une file bornée. Resend peut acheminer une notification au propriétaire. Les champs assainis et le rapport validé sont conservés dans un vault de leads séparé, jamais dans le vault personnel du propriétaire." },
    { heading: "Inférence locale et revue humaine", body: "La première lecture assistée par Gemma sera effectuée de façon asynchrone sur l'ordinateur du propriétaire, pas dans le navigateur du visiteur. Le modèle ne reçoit que les champs assainis et des connaissances publiques approuvées. Aucune décision commerciale ni aucun email ne part de façon autonome : Thomas relit le rapport et chaque brouillon avant de répondre." },
    { heading: "Conservation et suppression Project Clarity", body: "La durée de conservation opérationnelle prévue est de 30 jours à compter de la réception. Les enregistrements expirés de la file Cloudflare peuvent être purgés par le worker privé ; les notes locales expirées passent d’abord dans une corbeille récupérable et leur suppression définitive exige une confirmation humaine. Vous pouvez demander une suppression anticipée à bonjour@thomas-nicoli.com." },
    { heading: "Chat intelligent et résumés par email", body: "Cloudflare place le message et un contexte récent borné dans une file sécurisée. Un modèle Gemma open source exécuté localement via Ollama sur l’ordinateur de Thomas produit la réponse ; aucun fournisseur d’IA payant ne reçoit le contenu. Après chaque tour traité, un résumé est automatiquement envoyé à Thomas par Resend. Le chat ne demande pas l’email du visiteur et l’invite à ne pas partager de données sensibles." },
    { heading: "Session et conservation du chat", body: "Turnstile ouvre une session anonyme de deux heures, limitée à douze tours. L’adresse IP n’est utilisée que sous forme de hash pour la sécurité et les limites d’usage. Message, réponse, résumé et métadonnées minimales sont conservés 30 jours et peuvent être supprimés plus tôt sur demande à bonjour@thomas-nicoli.com." },
  ],
} as const;

export function getProjectClarityPrivacy(lang: Locale) {
  return additions[lang];
}
